#-------------------------------------- Window setting (floating, position, etc)
# for_window [class="Galendae"] floating enable, resize set 600 400, move absolute position 660 45
for_window [class="zoom"] floating enable, move position center
for_window [class="Xviewer"] floating enable, resize set 1000 600, move position center
for_window [class="Anki"] floating enable, move position center
for_window [class="Cheese"] floating enable, resize set 1200 800, move position center
for_window [class="Nitrogen"] floating enable, resize set  800 600, move position center
for_window [class="MintUpdate.py"] floating enable, resize set  1200 800, move position center
for_window [class="Drawing"] floating enable, resize set  800 600, move position center
for_window [title="xzoom"] floating enable, resize set  800 600, move position center
for_window [class="fcitx5-config-qt"] floating enable, resize set  800 600, move position center
for_window [class="Pavucontrol"] floating enable, move position center, resize set 800 600
for_window [title="Friends List"] floating enable, move position center
for_window [title="User 1 - Anki"] floating disable
# for_window [title="Meeting"] floating disable
# for_window [title="Zoom Workplace"] floating disable
for_window [title="nara230"] floating enable, resize set  800 600, move position center
for_window [class="Captain.py"] floating enable, resize set  800 600, move position center
for_window [title="i3switcherX11"] floating enable
for_window [title="Picture-in-Picture"] stick enable
for_window [class="kitty"] move position center

#-------------------------------------- Border
title_align center 
# for_window [class="^.*"] border normal 0 
for_window [all] border pixel 0
# for_window [all] title_format "%class %title"
# for_window [class="Anki"] title_format "%title"
# for_window [class="Anki"] border normal 0
for_window [class="kitty"] title_format "%title"
for_window [class="Code"] border pixel 0
for_window [class="obsidian"] border pixel 0
for_window [class="zen"] border pixel 0
for_window [class="kitty"] border pixel 0
# for_window [all] title_window_icon padding 3px

#--------------------------------------- Assign Workspaces:
assign [class="zen"] $ws3
assign [class="Spotify"] $ws10
assign [title="User 1 - Anki"] $ws8
assign [class="Nemo"] $ws2
assign [class="discord"] $ws9
assign [class="WebApp-WhatsApp5233"] $ws9
assign [class="obsidian"] $ws5
