
bindsym $mod+u exec --no-startup-id /home/yucandy16/.local/share/zen/zen 
bindsym $mod+y exec --no-startup-id nemo
bindsym $mod+i exec --no-startup-id dex /home/yucandy16/.local/share/applications/nvim.desktop
