bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

# Resize panes using Alt + h, j, k, l (no prefix)
#
bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5

# Bind h, j, k, l to switch panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# biar gak delay abis instert mode ke normal mode abis mencet esc
set -sg escape-time 10


# Split panes and inherit the active directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g allow-passthrough on

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
