bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

# Resize panes using Alt + h, j, k, l (no prefix)
#
bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5

# Bind h, j, k, l to switch panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# biar gak delay abis instert mode ke normal mode abis mencet esc
set -sg escape-time 10


# Split panes and inherit the active directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g allow-passthrough on

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
set -g @minimal-tmux-bg "#2ed1ab"
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "Morantron/tmux-fingers"

# set -g @plugin "semi710/minimal-tmux-status"

set -g @powerkit_transparent "true"
set -g @powerkit_theme "osaka-jade"
set -g @powerkit_theme_variant "default"

# Position the status bar at the bottom
set -g @powerkit_edge_separator_style "normal"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
set -g status-position bottom
set -g @plugin "fabioluciano/tmux-powerkit"
