# BEGIN_KITTY_THEME
# Obsidian
include current-theme.conf
# END_KITTY_THEME

# cursor_shape beam
cursor_trail 4
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 0
background_opacity 0.95 


# map ctrl+c copy_to_clipboard
# map ctrl+v paste_from_clipboard
# map ctrl+shift+c send_text all \x03

