volume=100
border=no
secondary-sub-pos=85  # Moves the secondary subtitle to 95% down
screenshot-directory=~/Pictures/mpv/
sub-auto=fuzzy
# Enable hardware decoding
hwdec=auto-safe

# Increase packet and backwards cache buffer
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=200MiB
